import type {
  CaregiverPatient,
  Game,
  HealthcareWorkerState,
  MemoryPack,
  NEState,
  PackObject,
  Reminder,
} from "./types";

export const DEMO_USER = {
  id: "asha-devi",
  name: "Asha Devi",
  age: 72,
  location: "Guwahati, Assam",
  language: "as" as const,
  avatarEmoji: "🌺",
};

export const DEMO_REMINDERS: Reminder[] = [
  {
    id: "rem-1",
    title: "Morning medicine",
    time: "08:00",
    days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    category: "medication",
    icon: "💊",
    enabled: true,
  },
  {
    id: "rem-2",
    title: "Gentle walk",
    time: "09:30",
    days: ["Mon", "Wed", "Fri"],
    category: "exercise",
    icon: "🚶",
    enabled: true,
  },
  {
    id: "rem-3",
    title: "Lunch with family",
    time: "13:00",
    days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    category: "meal",
    icon: "🍛",
    enabled: true,
  },
  {
    id: "rem-4",
    title: "Call granddaughter",
    time: "17:00",
    days: ["Sat", "Sun"],
    category: "social",
    icon: "📞",
    enabled: true,
  },
];

export const DEMO_MEMORY_PACKS: MemoryPack[] = [
  {
    id: "pack-1",
    title: "My Family",
    description: "Names and faces of loved ones",
    category: "Family",
    items: [
      "Granddaughter Priya",
      "Son Rohan",
      "Daughter-in-law Meera",
      "Grandson Arjun",
    ],
    emoji: "👨‍👩‍👧‍👦",
  },
  {
    id: "pack-2",
    title: "Festivals of Assam",
    description: "Bihu and other celebrations",
    category: "Culture",
    items: ["Bihu", "Magh Bihu", "Bohag Bihu", "Kati Bihu"],
    emoji: "🎉",
  },
  {
    id: "pack-3",
    title: "Childhood Home",
    description: "Places from growing up",
    category: "Home",
    items: [
      "The old banyan tree",
      "River Brahmaputra",
      "School in Nagaon",
      "The paddy fields",
    ],
    emoji: "🏡",
  },
  {
    id: "pack-4",
    title: "Favourite Recipes",
    description: "Dishes I love to cook",
    category: "Food",
    items: ["Masor Tenga", "Pitha", "Aloo Pitika", "Xaak Bhaji"],
    emoji: "🍲",
  },
];

/**
 * Pack-themed object sets used to theme the games. Each key matches the
 * `id` of a Familiar Memories pack selectable on the Profile page.
 */
export const PACK_THEMES: Record<string, PackObject[]> = {
  nature: [
    { emoji: "🌺", name: "Flower" },
    { emoji: "🌳", name: "Tree" },
    { emoji: "🦜", name: "Parrot" },
    { emoji: "🦋", name: "Butterfly" },
    { emoji: "🌾", name: "Paddy" },
    { emoji: "🐄", name: "Cow" },
    { emoji: "🐘", name: "Elephant" },
    { emoji: "🏔️", name: "Mountains" },
    { emoji: "🌊", name: "River" },
    { emoji: "🍃", name: "Leaf" },
    { emoji: "🌻", name: "Sunflower" },
    { emoji: "🦚", name: "Peacock" },
    { emoji: "🐝", name: "Bee" },
    { emoji: "🐸", name: "Frog" },
    { emoji: "🌴", name: "Palm" },
    { emoji: "🐦", name: "Bird" },
  ],
  "tea-food": [
    { emoji: "🍵", name: "Tea cup" },
    { emoji: "☕", name: "Tea" },
    { emoji: "🍛", name: "Curry" },
    { emoji: "🍚", name: "Rice" },
    { emoji: "🥭", name: "Mango" },
    { emoji: "🍌", name: "Banana" },
    { emoji: "🥣", name: "Bowl" },
    { emoji: "🫖", name: "Teapot" },
    { emoji: "🍯", name: "Honey" },
    { emoji: "🥜", name: "Peanut" },
    { emoji: "🍊", name: "Orange" },
    { emoji: "🥥", name: "Coconut" },
    { emoji: "🍲", name: "Stew" },
    { emoji: "🍮", name: "Dessert" },
    { emoji: "🍢", name: "Snack" },
    { emoji: "🌿", name: "Tea leaf" },
  ],
  household: [
    { emoji: "🏠", name: "House" },
    { emoji: "🪔", name: "Oil lamp" },
    { emoji: "🥣", name: "Bowl" },
    { emoji: "🪑", name: "Chair" },
    { emoji: "🛏️", name: "Bed" },
    { emoji: "🚪", name: "Door" },
    { emoji: "🪟", name: "Window" },
    { emoji: "🍳", name: "Pan" },
    { emoji: "🪣", name: "Bucket" },
    { emoji: "🧺", name: "Basket" },
    { emoji: "🪞", name: "Mirror" },
    { emoji: "🕯️", name: "Candle" },
    { emoji: "🧹", name: "Broom" },
    { emoji: "🪡", name: "Needle" },
    { emoji: "🧵", name: "Thread" },
    { emoji: "🫖", name: "Teapot" },
  ],
  crafts: [
    { emoji: "🧵", name: "Thread" },
    { emoji: "🪡", name: "Needle" },
    { emoji: "🧶", name: "Yarn" },
    { emoji: "🏺", name: "Pot" },
    { emoji: "🪵", name: "Wood" },
    { emoji: "🎋", name: "Bamboo" },
    { emoji: "🧺", name: "Basket" },
    { emoji: "🪶", name: "Feather" },
    { emoji: "🎨", name: "Paint" },
    { emoji: "🧣", name: "Scarf" },
    { emoji: "🪢", name: "Knot" },
    { emoji: "🧿", name: "Bead" },
    { emoji: "🪘", name: "Drum" },
    { emoji: "🪞", name: "Mirror" },
    { emoji: "🎋", name: "Bamboo" },
    { emoji: "🧵", name: "Loom" },
  ],
  music: [
    { emoji: "🎵", name: "Music" },
    { emoji: "🎶", name: "Notes" },
    { emoji: "🥁", name: "Drum" },
    { emoji: "🪕", name: "Banjo" },
    { emoji: "🎻", name: "Violin" },
    { emoji: "🎺", name: "Trumpet" },
    { emoji: "🪗", name: "Accordion" },
    { emoji: "🎤", name: "Mic" },
    { emoji: "🎹", name: "Piano" },
    { emoji: "🪘", name: "Drum" },
    { emoji: "🎷", name: "Sax" },
    { emoji: "🎸", name: "Guitar" },
    { emoji: "🪇", name: "Shaker" },
    { emoji: "🎼", name: "Score" },
    { emoji: "🎧", name: "Headphones" },
    { emoji: "🎵", name: "Song" },
  ],
  festivals: [
    { emoji: "🎉", name: "Party" },
    { emoji: "🪔", name: "Lamp" },
    { emoji: "🎊", name: "Confetti" },
    { emoji: "🎆", name: "Fireworks" },
    { emoji: "🎇", name: "Sparkler" },
    { emoji: "🥁", name: "Drum" },
    { emoji: "🌺", name: "Flower" },
    { emoji: "🍬", name: "Sweet" },
    { emoji: "🎁", name: "Gift" },
    { emoji: "🎈", name: "Balloon" },
    { emoji: "🎭", name: "Mask" },
    { emoji: "🎪", name: "Fair" },
    { emoji: "🍛", name: "Feast" },
    { emoji: "🎵", name: "Music" },
    { emoji: "🪅", name: "Piñata" },
    { emoji: "🪔", name: "Diya" },
  ],
  family: [
    { emoji: "👵", name: "Grandma" },
    { emoji: "👴", name: "Grandpa" },
    { emoji: "👨", name: "Father" },
    { emoji: "👩", name: "Mother" },
    { emoji: "👧", name: "Girl" },
    { emoji: "👦", name: "Boy" },
    { emoji: "👶", name: "Baby" },
    { emoji: "🧑", name: "Person" },
    { emoji: "👨‍👩‍👧", name: "Family" },
    { emoji: "🤝", name: "Hands" },
    { emoji: "💞", name: "Love" },
    { emoji: "🏡", name: "Home" },
    { emoji: "📸", name: "Photo" },
    { emoji: "🎂", name: "Cake" },
    { emoji: "🎁", name: "Gift" },
    { emoji: "🌺", name: "Flower" },
  ],
  landscapes: [
    { emoji: "🏔️", name: "Mountains" },
    { emoji: "🌊", name: "River" },
    { emoji: "🌄", name: "Sunrise" },
    { emoji: "🌅", name: "Sunset" },
    { emoji: "🌲", name: "Forest" },
    { emoji: "🌾", name: "Fields" },
    { emoji: "☁️", name: "Cloud" },
    { emoji: "🌧️", name: "Rain" },
    { emoji: "🌈", name: "Rainbow" },
    { emoji: "🏞️", name: "Valley" },
    { emoji: "🐘", name: "Elephant" },
    { emoji: "🦚", name: "Peacock" },
    { emoji: "🌺", name: "Flower" },
    { emoji: "🐦", name: "Bird" },
    { emoji: "⛰️", name: "Hill" },
    { emoji: "🌴", name: "Palm" },
  ],
};

export const DEMO_GAMES: Game[] = [
  {
    id: "memory-match",
    name: "Memory Match",
    description: "Flip cards and find matching pairs",
    skillArea: "Memory",
    icon: "🧠",
    color: "teal",
    difficulty: 2,
    durationMin: 5,
  },
  {
    id: "pattern-memory",
    name: "Pattern Memory",
    description: "Watch the tiles light up, then repeat the pattern",
    skillArea: "Memory",
    icon: "🎨",
    color: "indigo",
    difficulty: 2,
    durationMin: 5,
  },
  {
    id: "attention-focus",
    name: "Attention Game",
    description: "Spot the item that doesn't belong",
    skillArea: "Attention",
    icon: "🔍",
    color: "amber",
    difficulty: 2,
    durationMin: 4,
  },
  {
    id: "recognition",
    name: "Object Recognition",
    description: "Match the object to its name",
    skillArea: "Recognition",
    icon: "👤",
    color: "green",
    difficulty: 2,
    durationMin: 5,
  },
  {
    id: "routine-recall",
    name: "Daily Routine Recall",
    description: "Put the day's steps in order",
    skillArea: "RoutineRecall",
    icon: "🕰️",
    color: "violet",
    difficulty: 2,
    durationMin: 4,
  },
  {
    id: "engagement",
    name: "Story Time",
    description: "Answer gentle questions about a story",
    skillArea: "Engagement",
    icon: "📖",
    color: "rose",
    difficulty: 1,
    durationMin: 6,
  },
  {
    id: "mood-check",
    name: "Mood Check",
    description: "Share how you're feeling today",
    skillArea: "Engagement",
    icon: "💛",
    color: "amber",
    difficulty: 1,
    durationMin: 2,
  },
];

export const DEMO_CAREGIVER_PATIENTS: CaregiverPatient[] = [
  {
    id: "asha-devi",
    name: "Asha Devi",
    age: 72,
    relationship: "Mother",
    lastActive: "Today, 09:15",
    mood: "happy",
    adherence: 86,
    gamesPlayed: 24,
    streak: 6,
  },
  {
    id: "ram-nath",
    name: "Ram Nath",
    age: 78,
    relationship: "Father",
    lastActive: "Yesterday",
    mood: "calm",
    adherence: 72,
    gamesPlayed: 15,
    streak: 3,
  },
  {
    id: "lila-bai",
    name: "Lila Bai",
    age: 69,
    relationship: "Aunt",
    lastActive: "2 days ago",
    mood: "okay",
    adherence: 58,
    gamesPlayed: 9,
    streak: 1,
  },
];

export const DEMO_HEALTHCARE_WORKER: HealthcareWorkerState = {
  id: "hw-1",
  region: "Kamrup, Assam",
  patients: 42,
  activeToday: 18,
  avgAdherence: 74,
  alerts: 3,
  trend: [62, 65, 68, 66, 71, 73, 74],
};

export const DEMO_NE_STATES: NEState[] = [
  {
    id: "assam",
    name: "Assam",
    capital: "Dispur",
    language: "Assamese",
    emoji: "🌺",
    population: "3.1 crore",
    description:
      "Land of the Brahmaputra, tea gardens, and the vibrant Bihu festival.",
  },
  {
    id: "arunachal",
    name: "Arunachal Pradesh",
    capital: "Itanagar",
    language: "Multiple tribal languages",
    emoji: "🏔️",
    population: "13.8 lakh",
    description:
      "The 'Land of the Dawn-Lit Mountains', home to diverse tribal cultures.",
  },
  {
    id: "manipur",
    name: "Manipur",
    capital: "Imphal",
    language: "Meitei/Manipuri",
    emoji: "🦌",
    population: "28.6 lakh",
    description:
      "Known for its classical dance, polo's birthplace, and lush valleys.",
  },
  {
    id: "meghalaya",
    name: "Meghalaya",
    capital: "Shillong",
    language: "Khasi, Garo",
    emoji: "🌧️",
    population: "29.7 lakh",
    description:
      "The 'Abode of Clouds', famous for living root bridges and rain.",
  },
  {
    id: "mizoram",
    name: "Mizoram",
    capital: "Aizawl",
    language: "Mizo",
    emoji: "⛰️",
    population: "10.9 lakh",
    description:
      "A serene hill state with rolling mountains and warm communities.",
  },
  {
    id: "nagaland",
    name: "Nagaland",
    capital: "Kohima",
    language: "Multiple Naga languages",
    emoji: "🛕",
    population: "19.8 lakh",
    description:
      "Land of the Hornbill Festival and vibrant Naga tribal heritage.",
  },
  {
    id: "tripura",
    name: "Tripura",
    capital: "Agartala",
    language: "Bengali, Kokborok",
    emoji: "🏯",
    population: "36.7 lakh",
    description:
      "Known for its royal palaces, temples, and rich indigenous culture.",
  },
  {
    id: "sikkim",
    name: "Sikkim",
    capital: "Gangtok",
    language: "Nepali, Sikkimese",
    emoji: "🏔️",
    population: "6.1 lakh",
    description:
      "A Himalayan gem with monasteries, rhododendrons, and Mt. Kanchenjunga.",
  },
];
